services:
  - type: web
    name: acc-viewer-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: APS_CLIENT_ID
        sync: false
      - key: APS_CLIENT_SECRET
        sync: false
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production

